### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by haylogladiator** [mismith/clue#1]
How do you print a game, I tried the traditional control-p, but the preview did not show the full board.

**Comment by mismith** [comment]
Hmm, I remember this did print when I used it, and there is definitely still print-specific styling [here](https://github.com/mismith/clue/blob/master/src/main.css#L230), but I too can't seem to get it to print out properly. I'll take a peek

**Comment by mismith** [comment]
I've updated the print styling a bit. Still couldn't get the card laid out properly because print in CSS is pretty tough to wrangle properly due to poor browser support. Try Chrome in Landscape now though and it should be closer. You can tweak the source yourself to get it to your liking if you'd like :)
